import logging
import os
import shutil
import stat
import tempfile
from pathlib import Path
from typing import List
import git

logger = logging.getLogger(__name__)

INCLUDED_EXTENSIONS = {".py", ".js", ".ts", ".jsx", ".tsx", ".json", ".md"}
EXCLUDED_DIRS = {
    "node_modules", ".git", "__pycache__", ".venv", "venv", "env",
    "dist", "build", ".next", ".nuxt", "coverage", ".pytest_cache",
    ".mypy_cache", "eggs", ".eggs", ".cache", ".parcel-cache",
    ".turbo", ".svelte-kit", "out", "target", "vendor",
    ".idea", ".vscode", "site-packages",
}
# Filenames to skip outright (typically autogenerated, huge, or low-signal)
EXCLUDED_FILENAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml",
    "poetry.lock", "Pipfile.lock", "composer.lock",
}

MAX_FILE_BYTES = 500_000  # 500 KB per file: avoids OOM on lockfiles / minified JS
CLONE_TIMEOUT_SECONDS = 120


class IngestionError(Exception):
    """Raised when a repo cannot be ingested."""


def clone_repo(url: str, target_dir: str | None = None) -> str:
    """Clone a GitHub repo (shallow) and return the local path."""
    if target_dir is None:
        target_dir = tempfile.mkdtemp(prefix="codesage_")
    else:
        os.makedirs(target_dir, exist_ok=True)

    repo_name = url.rstrip("/").split("/")[-1].removesuffix(".git") or "repo"
    repo_path = os.path.join(target_dir, repo_name)

    if os.path.exists(repo_path):
        _force_rmtree(repo_path)

    # GitPython's kill_after_timeout is POSIX-only. Use git's built-in HTTP
    # low-speed timeout env vars instead — works on Windows and POSIX. If the
    # transfer drops below 1 KB/s for CLONE_TIMEOUT_SECONDS, git aborts.
    clone_env = {
        "GIT_HTTP_LOW_SPEED_LIMIT": "1000",
        "GIT_HTTP_LOW_SPEED_TIME": str(CLONE_TIMEOUT_SECONDS),
        "GIT_TERMINAL_PROMPT": "0",  # never prompt for credentials → fail fast on private repos
    }
    try:
        git.Repo.clone_from(
            url,
            repo_path,
            depth=1,
            single_branch=True,
            env=clone_env,
        )
    except git.GitCommandError as exc:
        _force_rmtree(target_dir)
        msg = str(exc).lower()
        if "not found" in msg or "could not read" in msg or "repository" in msg and "does not exist" in msg:
            raise IngestionError(f"Repository not found or inaccessible: {url}") from exc
        if "authentication" in msg or "permission" in msg:
            raise IngestionError("Repository requires authentication (private repo).") from exc
        raise IngestionError(f"Failed to clone repository: {exc}") from exc
    except Exception as exc:
        _force_rmtree(target_dir)
        raise IngestionError(f"Unexpected error while cloning: {exc}") from exc

    return repo_path


def scan_files(repo_path: str) -> List[str]:
    """Recursively scan repo and return filtered file paths."""
    repo_root = Path(repo_path)
    result = []

    for path in repo_root.rglob("*"):
        try:
            if not path.is_file():
                continue
        except OSError:
            continue
        if _is_excluded(path, repo_root):
            continue
        if path.name in EXCLUDED_FILENAMES:
            continue
        if path.suffix.lower() not in INCLUDED_EXTENSIONS:
            continue
        try:
            size = path.stat().st_size
        except OSError:
            continue
        if size == 0 or size > MAX_FILE_BYTES:
            continue
        result.append(str(path))

    return result


def _is_excluded(path: Path, root: Path) -> bool:
    try:
        relative = path.relative_to(root)
    except ValueError:
        return True
    for part in relative.parts[:-1]:  # skip filename itself
        if part in EXCLUDED_DIRS or part.endswith(".egg-info") or part.startswith("."):
            # Hidden directories (starting with .) are typically not source
            if part in {".github"}:
                continue
            return True
    return False


def cleanup_repo(repo_path: str) -> None:
    """Remove the cloned repo. Safe to call multiple times."""
    if not repo_path:
        return
    parent = str(Path(repo_path).parent)
    tmp_root = os.path.realpath(tempfile.gettempdir())
    if os.path.realpath(parent).startswith(tmp_root):
        _force_rmtree(parent)


def _on_rm_error(func, path, exc_info):
    """Handler for shutil.rmtree to deal with read-only files (common on Windows .git)."""
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except OSError:
        logger.debug("Could not remove %s during cleanup", path)


def _force_rmtree(path: str) -> None:
    if os.path.exists(path):
        shutil.rmtree(path, onerror=_on_rm_error)
